Repository test-fullautomation/python-jsonpreprocessor, pull requests merged in 2023-10, with the labels that each got.

#158 Added self test cases JPP_0507, JPP_0508, JPP_0509
  test/JPP_TestUsecases.csv
  test/JPP_TestUsecases.html
  test/JPP_TestUsecases.rst
  test/JPP_TestUsecases.txt
  test/component_test.py
  test/pytest/pytestfiles/test_07_COMPOSITE_EXPRESSIONS_GOODCASE.py
  test/testconfig/TestConfig.py
  test/testfiles/jpp-test_config_0507.jsonp
  test/testfiles/jpp-test_config_0508.jsonp
  test/testfiles/jpp-test_config_0509.jsonp
Labels: enhancement, 0.9.0

#160 Extended self test JPP_1000; added self test JPP_1001
  test/JPP_TestUsecases.csv
  test/JPP_TestUsecases.html
  test/JPP_TestUsecases.rst
  test/JPP_TestUsecases.txt
  test/component_test.py
  test/pytest/pytestfiles/test_11_IMPLICIT_CREATION_GOODCASE.py
  test/testconfig/TestConfig.py
  test/testfiles/import/import.1/jpp-test_config_implicit_creation.1.1.jsonp
  test/testfiles/jpp-test_config_0508.jsonp
  test/testfiles/jpp-test_config_1001.jsonp
Labels: enhancement, 0.9.0

#165 Activated test cases JPP_0358, JPP_0356, JPP_0355, JPP_0005, JPP_0207
  test/JPP_TestUsecases.csv
  test/JPP_TestUsecases.html
  test/JPP_TestUsecases.rst
  test/JPP_TestUsecases.txt
  test/component_test.py
  test/pytest/pytestfiles/test_01_DATA_TYPES_GOODCASE.py
  test/pytest/pytestfiles/test_02_DATA_INTEGRITY_GOODCASE.py
  test/pytest/pytestfiles/test_03_PARAMETER_SUBSTITUTION_GOODCASE.py
  test/pytest/pytestfiles/test_04_PARAMETER_SUBSTITUTION_BADCASE.py
  test/pytest/pytestfiles/test_05_VALUE_DETECTION_GOODCASE.py
  test/pytest/pytestfiles/test_06_VALUE_DETECTION_BADCASE.py
  test/pytest/pytestfiles/test_07_COMPOSITE_EXPRESSIONS_GOODCASE.py
  test/pytest/pytestfiles/test_08_COMPOSITE_EXPRESSIONS_BADCASE.py
  test/pytest/pytestfiles/test_09_COMMON_SYNTAX_VIOLATIONS_GOODCASE.py
  test/pytest/pytestfiles/test_10_COMMON_SYNTAX_VIOLATIONS_BADCASE.py
  test/pytest/pytestfiles/test_11_IMPLICIT_CREATION_GOODCASE.py
  test/pytest/pytestfiles/test_12_CYCLIC_IMPORTS_BADCASE.py
  test/pytest/pytestfiles/test_13_PATH_FORMATS_GOODCASE.py
  test/testconfig/TestConfig.py
Labels: 0.9.0

#166 Namsonx/task/stabi branch
  JsonPreprocessor/CJsonPreprocessor.py
  test/JPP_TestUsecases.csv
  test/JPP_TestUsecases.html
  test/JPP_TestUsecases.rst
  test/JPP_TestUsecases.txt
  test/component_test.py
  test/pytest/pytestfiles/test_01_DATA_TYPES_GOODCASE.py
  test/pytest/pytestfiles/test_02_DATA_INTEGRITY_GOODCASE.py
  test/pytest/pytestfiles/test_03_PARAMETER_SUBSTITUTION_GOODCASE.py
  test/pytest/pytestfiles/test_04_PARAMETER_SUBSTITUTION_BADCASE.py
  test/pytest/pytestfiles/test_05_VALUE_DETECTION_GOODCASE.py
  test/pytest/pytestfiles/test_06_VALUE_DETECTION_BADCASE.py
  test/pytest/pytestfiles/test_07_COMPOSITE_EXPRESSIONS_GOODCASE.py
  test/pytest/pytestfiles/test_08_COMPOSITE_EXPRESSIONS_BADCASE.py
  test/pytest/pytestfiles/test_09_COMMON_SYNTAX_VIOLATIONS_GOODCASE.py
  test/pytest/pytestfiles/test_10_COMMON_SYNTAX_VIOLATIONS_BADCASE.py
  test/pytest/pytestfiles/test_11_IMPLICIT_CREATION_GOODCASE.py
  test/pytest/pytestfiles/test_12_CYCLIC_IMPORTS_BADCASE.py
  test/pytest/pytestfiles/test_13_PATH_FORMATS_GOODCASE.py
  test/testconfig/TestConfig.py
Labels: enhancement, 0.9.0

#169 Fixed bug 223 - parameter substitution doesn't work properly
  JsonPreprocessor/CJsonPreprocessor.py
Labels: enhancement, 0.9.0

#170 Added release item file for Release Info Tool
  config/robotframework_aio/release_items_JsonPreprocessor.json
Labels: documentation, 0.10.0

#172 Tiny change to fix the issue occur in TSM_0200
  JsonPreprocessor/CJsonPreprocessor.py
Labels: enhancement, 0.10.0
