Repository test-fullautomation/python-jsonpreprocessor, pull requests merged in 2023-01, with the labels that each got.

#33 tiny fixes
  README.md
  README.rst
Labels: 0.6.0

#38 Update to reduce redundant parts of documentation
  JsonPreprocessor/CJsonPreprocessor.py
Labels: documentation, 0.6.0

#37 Update documentation base on new version
  JsonPreprocessor/JsonPreprocessor.pdf
  README.md
  README.rst
  doc/CJsonPreprocessor.rst
  doc/_build/html/.buildinfo
  doc/_build/html/CJsonPreprocessor.html
  doc/_build/html/_images/python3-jsonpreprocessor.png
  doc/_build/html/_modules/CJsonPreprocessor.html
  doc/_build/html/_modules/index.html
  doc/_build/html/_sources/CJsonPreprocessor.rst.txt
  doc/_build/html/_sources/additional_doc/feature_documentation.rst.txt
  doc/_build/html/_sources/index.rst.txt
  doc/_build/html/_static/alabaster.css
  doc/_build/html/_static/basic.css
  doc/_build/html/_static/custom.css
  doc/_build/html/_static/doctools.js
  doc/_build/html/_static/documentation_options.js
  doc/_build/html/_static/file.png
  doc/_build/html/_static/jquery-3.5.1.js
  doc/_build/html/_static/jquery.js
  doc/_build/html/_static/language_data.js
  doc/_build/html/_static/minus.png
  doc/_build/html/_static/plus.png
  doc/_build/html/_static/pygments.css
  doc/_build/html/_static/searchtools.js
  doc/_build/html/_static/underscore-1.13.1.js
  doc/_build/html/_static/underscore.js
  doc/_build/html/additional_doc/feature_documentation.html
  doc/_build/html/genindex.html
  doc/_build/html/index.html
  doc/_build/html/objects.inv
  doc/_build/html/py-modindex.html
  doc/_build/html/search.html
  doc/_build/html/searchindex.js
  doc/_build/latex/Json-Preprocessor.pdf
  doc/additional_doc/feature_documentation.rst
  doc/conf.py
  doc/images/python3-jsonpreprocessor.png
  doc/index.rst
  doc/latex_addons/sphinxlatexadmonitions.sty
  packagedoc/additional_docs/Description.rst
Labels: documentation, 0.6.0

#41 Fix issue40 - single quotes error
  JsonPreprocessor/CJsonPreprocessor.py
Labels: enhancement, 0.6.0

#42 Fix issue34 - absolute paths in sample
  sample/001_sample_comments.py
  sample/003_sample_import.py
  sample/005_sample_python_syntax.py
  sample/007_sample_use_of_variables.py
Labels: enhancement, 0.6.0

#43 Adds encoding when load config files to support utf8 characters
  JsonPreprocessor/CJsonPreprocessor.py
Labels: enhancement, 0.6.0

#46 fix error when executing test-trigger
  .gitignore
  atest/jsonpreprocessor/test_jsonpreprocessor.py
Labels: enhancement, 0.7.0
