Repository test-fullautomation/python-jsonpreprocessor, pull requests merged in 2024-04, with the labels that each got.

#271 Namsonx/task/stabi branch
  JsonPreprocessor/CJsonPreprocessor.py
  config/robotframework_aio/release_items_JsonPreprocessor.json
  test/JPP_TestUsecases.csv
  test/JPP_TestUsecases.html
  test/JPP_TestUsecases.rst
  test/JPP_TestUsecases.txt
  test/component_test.py
  test/pytest/pytestfiles/test_18_LINE_BREAKS_GOODCASE.py
  test/pytest/pytestfiles/test_19_SELF_ASSIGNMENTS_GOODCASE.py
  test/pytest/pytestfiles/test_20_ASSIGNMENTS_BY_REFERENCE_GOODCASE.py
  test/testconfig/TestConfig.py
  test/testfiles/jpp-test_config_1700.jsonp
  test/testfiles/jpp-test_config_1800.jsonp
Labels: enhancement, 0.11.0

#273 Self test maintenance
  test/JPP_TestUsecases.csv
  test/JPP_TestUsecases.html
  test/JPP_TestUsecases.rst
  test/JPP_TestUsecases.txt
  test/component_test.py
  test/pytest/pytestfiles/test_07_COMPOSITE_EXPRESSIONS_GOODCASE.py
  test/pytest/pytestfiles/test_16_STRING_INDICES_GOODCASE.py
  test/pytest/pytestfiles/test_20_ASSIGNMENTS_BY_REFERENCE_GOODCASE.py
  test/testconfig/TestConfig.py
  test/testfiles/jpp-test_config_1500.jsonp
  test/testfiles/jpp-test_config_1501.jsonp
  test/testfiles/jpp-test_config_1900.jsonp
Labels: selftest, 0.11.0

#281 Extended debugging support
  JsonPreprocessor/CJsonPreprocessor.py
  JsonPreprocessor/JsonPreprocessor.pdf
  JsonPreprocessor/version.py
  config/robotframework_aio/release_items_JsonPreprocessor.json
  packagedoc/additional_docs/History.tex
Labels: enhancement, 0.11.0

#284 tiny typo
  JsonPreprocessor/CJsonPreprocessor.py
Labels: enhancement, 0.11.0

#283 Namsonx/task/stabi branch
  JsonPreprocessor/CJsonPreprocessor.py
  JsonPreprocessor/JsonPreprocessor.pdf
  JsonPreprocessor/version.py
  config/robotframework_aio/release_items_JsonPreprocessor.json
  packagedoc/additional_docs/History.tex
  test/JPP_TestUsecases.csv
  test/JPP_TestUsecases.html
  test/JPP_TestUsecases.rst
  test/JPP_TestUsecases.txt
  test/component_test.py
  test/pytest/pytestfiles/test_07_COMPOSITE_EXPRESSIONS_GOODCASE.py
  test/pytest/pytestfiles/test_16_STRING_INDICES_GOODCASE.py
  test/pytest/pytestfiles/test_20_ASSIGNMENTS_BY_REFERENCE_GOODCASE.py
  test/testconfig/TestConfig.py
  test/testfiles/jpp-test_config_1500.jsonp
  test/testfiles/jpp-test_config_1501.jsonp
  test/testfiles/jpp-test_config_1900.jsonp
Labels: enhancement, 0.11.0

#292 Code snippet generator extended ('+' / '-' combinations in indices)
  test/testtools/GenSnippetsJPP.py
Labels: enhancement, 0.12.0
