Repository test-fullautomation/python-jsonpreprocessor, pull requests merged in 2024-05, with the labels that each got.

#295 Documentation updated (JSONP format)
  JsonPreprocessor/JsonPreprocessor.pdf
  packagedoc/additional_docs/Appendix.rst
  packagedoc/additional_docs/Description.tex
  packagedoc/additional_docs/History.tex
  packagedoc/additional_docs/Introduction.tex
  packagedoc/additional_docs/The JSONP format.tex
Labels: documentation, 0.12.0

#299 Description of JSONP format extended (Dynamic parameter names)
  JsonPreprocessor/JsonPreprocessor.pdf
  config/robotframework_aio/release_items_JsonPreprocessor.json
  packagedoc/additional_docs/The JSONP format.tex
  requirements.txt
Labels: documentation, 0.12.0

#302 add step to install requirements file for publish pypi workflow
  .github/workflows/python-publish.yml
  JsonPreprocessor/JsonPreprocessor.pdf
  JsonPreprocessor/version.py
  packagedoc/additional_docs/History.tex
Labels: bug, 0.12.0

#303 add pydotdict as this package dependencies
  config/repository_config.json
Labels: enhancement, 0.12.0

#309 Namsonx/task/stabi branch
  JsonPreprocessor/CJsonPreprocessor.py
  JsonPreprocessor/JsonPreprocessor.pdf
  packagedoc/additional_docs/The JSONP format.tex
Labels: enhancement, 0.12.1

#310 Adapted wording in history
  JsonPreprocessor/JsonPreprocessor.pdf
  packagedoc/additional_docs/History.tex
Labels: documentation, 0.12.1
